### ISSUE TITLE
关于部署的问题

### ISSUE THREAD

**Issue by 963029755** [itimor/django-oms#20]
关于部署的时候 执行到
5.拉取代码
mkdir -p /data/projects/
cd !$
git clone git@bitbucket.org:larrytblucky/oms.git

发生了报错
![image](https://user-images.githubusercontent.com/46158660/57226750-3f14f000-7042-11e9-974e-c265d73df5da.png)
 这个怎么解决呢？

**Comment by 963029755** [comment]
关于部署这个项目 能否加您 因为在Django运行 报错是为什么呢？
# 生成数据库文件
# 把每个模块 makemigrations
python manage.py makemigrations 模块名

(omsname) [root@iZ2zecxoj2ald2o7ij7rcjZ omsBackend]# python manage.py makemigrations test0510
开发环境
Traceback (most recent call last):
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f95619a9208>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='1.1.1.11', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f95619a9208>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/root/.virtualenvs/omsname/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/data/projects/django-oms/omsBackend/omsBackend/settings/__init__.py", line 13, in <module>
    from omsBackend.settings.dev import *
  File "/data/projects/django-oms/omsBackend/omsBackend/settings/dev.py", line 77, in <module>
    sapi = SaltAPI(url=salt_info["url"], username=salt_info["username"], password=salt_info["password"])
  File "/data/projects/django-oms/omsBackend/salts/saltapi.py", line 19, in __init__
    self.__token = self.get_token()
  File "/data/projects/django-oms/omsBackend/salts/saltapi.py", line 32, in get_token
    req = requests.post(loginurl, data=data, headers=self.__header, verify=False)
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/root/.virtualenvs/omsname/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='1.1.1.11', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f95619a9208>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by longlyjack** [comment]
我也是同样问题 没有解决

**Comment by 963029755** [comment]
我想可能是没有添加模块的原因 。。。 但是没找到在哪里修改 setting.py这个文件

**Comment by hhhnb** [comment]
有没有具体 的安装步骤啊   这个不太会安装   以前都是玩install.php的

**Comment by 963029755** [comment]
同样没有解决问题 是超时链接的问题

**Comment by YWXcici** [comment]
有人解决了么？都没找到问题出在哪

**Comment by 963029755** [comment]
最近事情太多了 没时间看这个了

**Comment by PejaZhang** [comment]
requests.exceptions.SSLError: HTTPSConnectionPool(**host='1.1.1.11', port=8888**): Max retries exceeded with url: /login (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:777)'),))

这是要去请求哪个url，**1.1.1.11**这个IP肯定是不对的吧？？
