### ISSUE TITLE
初始化数据库出问题，作者要是方便留个联系方式好吗，谢谢了

### ISSUE THREAD

**Issue by YWXcici** [itimor/django-oms#21]
开发环境
Traceback (most recent call last):
  File "G:\python\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "G:\python\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "G:\python\lib\site-packages\django\core\management\__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "G:\python\lib\site-packages\django\conf\__init__.py", line 57, in __getattr__
    self._setup(name)
  File "G:\python\lib\site-packages\django\conf\__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "G:\python\lib\site-packages\django\conf\__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "G:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\颜CICI\django-oms\omsBackend\omsBackend\settings\__init__.py", line 13, in <module>
    from omsBackend.settings.dev import *
  File "C:\Users\颜CICI\django-oms\omsBackend\omsBackend\settings\dev.py", line 77, in <module>
    sapi = SaltAPI(url=salt_info["url"], username=salt_info["username"], password=salt_info["password"])
  File "C:\Users\颜CICI\django-oms\omsBackend\salts\saltapi.py", line 19, in __init__
    self.__token = self.get_token()
  File "C:\Users\颜CICI\django-oms\omsBackend\salts\saltapi.py", line 32, in get_token
    req = requests.post(loginurl, data=data, headers=self.__header, verify=False)
  File "G:\python\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "G:\python\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "G:\python\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "G:\python\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "G:\python\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "G:\python\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "G:\python\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "G:\python\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "G:\python\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File "G:\python\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "G:\python\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
KeyboardInterrupt

C:\Users\颜CICI\django-oms\omsBackend>python manage.py makemigrations omsBackend
开发环境
Traceback (most recent call last):
  File "G:\python\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "G:\python\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "G:\python\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\python\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "G:\python\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "G:\python\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "G:\python\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File "G:\python\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0376D1B0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没
有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\python\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "G:\python\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "G:\python\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='1.1.1.11', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSC
onnection object at 0x0376D1B0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "G:\python\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "G:\python\lib\site-packages\django\core\management\__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "G:\python\lib\site-packages\django\conf\__init__.py", line 57, in __getattr__
    self._setup(name)
  File "G:\python\lib\site-packages\django\conf\__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "G:\python\lib\site-packages\django\conf\__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "G:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\颜CICI\django-oms\omsBackend\omsBackend\settings\__init__.py", line 13, in <module>
    from omsBackend.settings.dev import *
  File "C:\Users\颜CICI\django-oms\omsBackend\omsBackend\settings\dev.py", line 77, in <module>
    sapi = SaltAPI(url=salt_info["url"], username=salt_info["username"], password=salt_info["password"])
  File "C:\Users\颜CICI\django-oms\omsBackend\salts\saltapi.py", line 19, in __init__
    self.__token = self.get_token()
  File "C:\Users\颜CICI\django-oms\omsBackend\salts\saltapi.py", line 32, in get_token
    req = requests.post(loginurl, data=data, headers=self.__header, verify=False)
  File "G:\python\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "G:\python\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "G:\python\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "G:\python\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "G:\python\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='1.1.1.11', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTT
PSConnection object at 0x0376D1B0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by typ431127** [comment]
这是salt地址没改，要改成你自己的地址
