### ISSUE TITLE
运行init.py的时候报错了。另现在demo看不了了，504了

### ISSUE THREAD

**Issue by SlamDunkDcc** [itimor/django-oms#4]
开发环境
Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/DCC/django-oms/omsBackend/omsBackend/settings/__init__.py", line 13, in <module>
    from omsBackend.settings.dev import *
  File "/DCC/django-oms/omsBackend/omsBackend/settings/dev.py", line 77, in <module>
    sapi = SaltAPI(url=salt_info["url"], username=salt_info["username"], password=salt_info["password"])
  File "/DCC/django-oms/omsBackend/salts/saltapi.py", line 16, in __init__
    self.__token = self.get_token()
  File "/DCC/django-oms/omsBackend/salts/saltapi.py", line 29, in get_token
    req = requests.post(loginurl, data=data, headers=self.__header, verify=False)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 108, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))

**Comment by Eric-Hu-Windy** [comment]
我也是看不了demo，不过是400，{"non_field_errors":["无法使用提供的认证信息登录。"]}

**Comment by yang3259** [comment]
demo登录不上

**Comment by bbotte** [comment]
> 你的这个问题是salt-api没有配置

请问salt-api 怎么设置，没找到设置的信息
